
Ksrc/main/java/com/isb/journal/entity/norelacional/AccountingCostCenter.java
Isrc/main/java/com/isb/journal/entity/relacional/AccountingCostCenter.java
8src/main/java/com/isb/journal/ApiJournalApplication.java
<src/main/java/com/isb/journal/exception/BadRequestError.java
=src/main/java/com/isb/journal/controller/ControllerMongo.java
>src/main/java/com/isb/journal/controller/ControllerOracle.java
Esrc/main/java/com/isb/journal/repository/database/DataBaseConfig.java
:src/main/java/com/isb/journal/exception/ErrorNotFound.java
Asrc/main/java/com/isb/journal/controller/ErrorRestController.java
=src/main/java/com/isb/journal/exception/GenericException.java
Isrc/main/java/com/isb/journal/entity/norelacional/JournalEntityMongo.java
Hsrc/main/java/com/isb/journal/entity/relacional/JournalEntityOracle.java
8src/test/java/com/isb/journal/test/JournalMongoTest.java
Ksrc/main/java/com/isb/journal/entity/norelacional/JournalOperationData.java
Isrc/main/java/com/isb/journal/entity/relacional/JournalOperationData.java
Nsrc/main/java/com/isb/journal/entity/norelacional/JournalOperationRequest.java
Lsrc/main/java/com/isb/journal/entity/relacional/JournalOperationRequest.java
9src/test/java/com/isb/journal/test/JournalOracleTest.java
Bsrc/main/java/com/isb/journal/model/ModelAccountingCostCenter.java
Asrc/main/java/com/isb/journal/model/ModelJournalDataResponse.java
Bsrc/main/java/com/isb/journal/model/ModelJournalOperationData.java
3src/main/java/com/isb/journal/model/ModelLinks.java
=src/main/java/com/isb/journal/model/ModelObbSpecificData.java
=src/main/java/com/isb/journal/model/ModelOperationAmount.java
>src/main/java/com/isb/journal/model/ModelTargetCostCenter.java
<src/main/java/com/isb/journal/model/ModelUserCostCenter.java
Fsrc/main/java/com/isb/journal/entity/norelacional/ObbSpecificData.java
Dsrc/main/java/com/isb/journal/entity/relacional/ObbSpecificData.java
Fsrc/main/java/com/isb/journal/entity/norelacional/OperationAmount.java
Dsrc/main/java/com/isb/journal/entity/relacional/OperationAmount.java
pom.xml
Csrc/main/java/com/isb/journal/repository/RepositoryDataListDTO.java
@src/main/java/com/isb/journal/repository/RepositoryMongoDTO.java
Asrc/main/java/com/isb/journal/repository/RepositoryOracleDTO.java
>src/main/java/com/isb/journal/config/SwaggerConfiguration.java
Gsrc/main/java/com/isb/journal/entity/norelacional/TargetCostCenter.java
Esrc/main/java/com/isb/journal/entity/relacional/TargetCostCenter.java
Esrc/main/java/com/isb/journal/entity/norelacional/UserCostCenter.java
Csrc/main/java/com/isb/journal/entity/relacional/UserCostCenter.java