spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
      uri: mongodb://localhost/test
  datasource:
    url: jdbc:mysql://localhost:3306/Journal?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC  
    username: root
    password: root
  jpa:  
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect 
    #driver-class-name: com.mysql.jdbc.Driver
# security:
#   oauth2:
#     resource:
#       filter-order: 3   

server:
  port: 8081

