
Jsrc/main/java/com/isb/interapplication/ApiInterapplicationApplication.java
Esrc/main/java/com/isb/interapplication/exception/BadRequestError.java
Asrc/main/java/com/isb/interapplication/controller/Controller.java
Isrc/main/java/com/isb/interapplication/exception/ErrorInternalServer.java
Csrc/main/java/com/isb/interapplication/exception/ErrorNotFound.java
Jsrc/main/java/com/isb/interapplication/controller/ErrorRestController.java
Fsrc/main/java/com/isb/interapplication/exception/GenericException.java
Isrc/main/java/com/isb/interapplication/entity/InterapplicationEntity.java
Osrc/main/java/com/isb/interapplication/entity/InterapplicationOrderRequest.java
Tsrc/main/java/com/isb/interapplication/repository/InterapplicationRepositoryDTO.java
Fsrc/test/java/com/isb/interapplication/test/InterapplicationTests.java
Csrc/main/java/com/isb/interapplication/model/ModelDataResponse.java
Fsrc/main/java/com/isb/interapplication/model/ModelOperationAmount.java
Gsrc/main/java/com/isb/interapplication/model/ModelSourceCostCenter.java
Gsrc/main/java/com/isb/interapplication/model/ModelTargetCostcenter.java
Bsrc/main/java/com/isb/interapplication/entity/OperationAmount.java
pom.xml
Csrc/main/java/com/isb/interapplication/entity/SourceCostCenter.java
Gsrc/main/java/com/isb/interapplication/config/SwaggerConfiguration.java
Csrc/main/java/com/isb/interapplication/entity/TargetCostCenter.java