
Osrc/main/java/com/isb/conciliator/ApiGlobalMovementsConciliatorApplication.java
Ysrc/test/java/com/isb/conciliator/test/ApiGlobalMovementsConciliatorApplicationTests.java
@src/main/java/com/isb/conciliator/exception/BadRequestError.java
Bsrc/main/java/com/isb/conciliator/entity/CertificationMsgData.java
?src/main/java/com/isb/conciliator/entity/ConciliatorEntity.java
6src/main/java/com/isb/conciliator/entity/Contract.java
<src/main/java/com/isb/conciliator/controller/Controller.java
>src/main/java/com/isb/conciliator/exception/ErrorNotFound.java
Esrc/main/java/com/isb/conciliator/controller/ErrorRestController.java
Asrc/main/java/com/isb/conciliator/exception/GenericException.java
Fsrc/main/java/com/isb/conciliator/model/ModelCertificationMsgData.java
:src/main/java/com/isb/conciliator/model/ModelContract.java
@src/main/java/com/isb/conciliator/model/ModelMovementAmount.java
Gsrc/main/java/com/isb/conciliator/model/ModelMovementsDataResponse.java
<src/main/java/com/isb/conciliator/entity/MovementAmount.java
pom.xml
?src/main/java/com/isb/conciliator/repository/RepositoryDTO.java
Bsrc/main/java/com/isb/conciliator/config/SwaggerConfiguration.java